print('Введите первый список:')
X = input().split()
print('Введите второй список:')
Y = input().split()
X1 = list(map(int, X))
Y1 = list(map(int, Y))
X1.extend([0] * (len(Y1) - len(X1)))
Y1.extend([0] * (len(X1) - len(Y1)))
Res = list(map(lambda X1, Y1: X1 + Y1, X1, Y1))
print('Результат: ', Res)