# -*- coding: utf-8 -*-
"""Homework5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wcyx9gZ6Z1vQ9-8ZqmiYFPggxm6BNAGm
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/Customers (1).csv', delimiter = ';')
df

df.isnull().any()

df.dropna()

df.groupby('Profession')['Income'].mean()