# -*- coding: utf-8 -*-
"""Homework8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6KbFeEcmiySgGjypQz-sSnwXXq0EZzQ
"""

import numpy as np

arr = np.random.randint(1, 10, size=100)
(arr > 7).mean() * 100

b = 0
for i in range(1000):
  arr = np.random.randint(1, 10, size=100)
  a = (arr > 7).mean() * 100
  if a == 20:
    b += 1
print(b/1000)

arr = np.array([np.arange(1, 11)] * 10)
arr

arr.sum(axis=0)